Repository willianrod/ODeck, pull requests merged in 2023-08, with the labels that each got.

#20 feat: readme in spanish
  README.md
  docs/README_ESP.md
Labels: approved

#22 fix(hotkey): allow hotkey with commas
  src/renderer/components/Form/InputBindings/index.tsx
  src/renderer/components/editor/index.tsx
Labels: bug, approved

#24 fix: use cwd option on executable-handler
  src/server/handlers/executable-handler.ts
Labels: approved

#30 feat: :sparkles: Adds keys state to allow toggle keys
  src/renderer/components/key/index.tsx
Labels: changes requested

#28 Feat: Delete Device function
  src/renderer/components/CreatePageButton/index.tsx
  src/renderer/components/DeleteWarnModal/index.tsx
  src/renderer/i18n/locales/en-US/delete-warn.json
  src/renderer/i18n/locales/en-US/index.ts
  src/renderer/i18n/locales/pt-BR/delete-warn.json
  src/renderer/i18n/locales/pt-BR/index.ts
  src/renderer/pages/start/index.tsx
  src/renderer/redux/ducks/devices.ts
  src/server/controllers/devices.ts
  src/server/enums/event-types.enum.ts
  src/server/index.ts
Labels: enhancement, approved
